// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA758tiXTn2BacjHaJwUNmTWYcyv0ZhlUA',
    appId: '1:299233562742:web:c317dc197dc7ce28b54f57',
    messagingSenderId: '299233562742',
    projectId: 'flutterbankingapplicatio-54e67',
    authDomain: 'flutterbankingapplicatio-54e67.firebaseapp.com',
    storageBucket: 'flutterbankingapplicatio-54e67.appspot.com',
    measurementId: 'G-G6X5J1XS46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRzL345bNjiumd443WCW_1U7EzaDsheg',
    appId: '1:299233562742:android:04e11d87b3b782d8b54f57',
    messagingSenderId: '299233562742',
    projectId: 'flutterbankingapplicatio-54e67',
    storageBucket: 'flutterbankingapplicatio-54e67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYPqXpamt-MLkF3FziuivAw1ZZKtkwPl4',
    appId: '1:299233562742:ios:70da4007281031acb54f57',
    messagingSenderId: '299233562742',
    projectId: 'flutterbankingapplicatio-54e67',
    storageBucket: 'flutterbankingapplicatio-54e67.appspot.com',
    iosBundleId: 'com.example.bankingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYPqXpamt-MLkF3FziuivAw1ZZKtkwPl4',
    appId: '1:299233562742:ios:6f72ee7dbc1858edb54f57',
    messagingSenderId: '299233562742',
    projectId: 'flutterbankingapplicatio-54e67',
    storageBucket: 'flutterbankingapplicatio-54e67.appspot.com',
    iosBundleId: 'com.example.bankingApplication.RunnerTests',
  );
}
